CC = g++
target = 1_1.o 1_2.o 1_3.o 1_4.o 1_5.o
all : $(target)
1_1.o : 1_1.cpp
	$(CC) -o $@ $?

1_2.o : 1_2.cpp
	$(CC) -o $@ $?

1_3.o : 1_3.cpp
	$(CC) -o $@ $?

1_4.o : 1_4.cpp
	$(CC) -o $@ $?

1_5.o : 1_5.cpp
	$(CC) -o $@ $?

clean:
	rm $(target)